name: shoplist
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # List Dependencies
  flutter_reorderable_list: ^1.0.0
  receive_sharing_intent: ^1.4.5
  flutter_slidable: ^1.2.0
  speech_to_text: ^5.4.3
  google_ml_kit: ^0.7.3
  image_picker: ^0.8.5
  provider: ^6.0.2

  # Styling Dependencies
  google_fonts: ^2.1.0
  avatar_glow: ^2.0.2
  flutter_svg: ^1.0.3
  lints: ^1.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lists/0.png
    - assets/lists/1.png
    - assets/lists/2.png
    - assets/lists/3.png
    - assets/lists/4.png
    - assets/lists/5.png
    - assets/lists/6.png
    - assets/lists/7.png
    - assets/lists/8.png
    - assets/lists/9.png
    - assets/lists/10.png
    - assets/lists/11.png
    - assets/lists/diary.png
    - assets/lists/meat.png
    - assets/emptylist.svg
    - assets/share.svg
    - assets/scan.svg
    - assets/loading.gif
    - assets/google_fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
